syntax on

" Case insensitive search except when using capital letters"
set ignorecase
set smartcase

set number

" Indentation and shifting offset"
set expandtab
set tabstop=4
set shiftwidth=4

" Delete 4 tabs when using backspace after tabbing"
set softtabstop=4

set termguicolors

" Remove pipe charecters from vertical split
" Preserve trailing space after \ here: don't trim trailing whitespace
set fillchars+=vert:\ 

nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

" Write file with sudo rights: sudo tee the same file
cmap w!! w !sudo tee > /dev/null %

colorscheme getafe

