unbind r
bind r source-file ~/.config/tmux/.tmux.conf

set-option -g status-position top
set -g mouse on
set -g base-index 1
# Set leader key
set -g prefix C-j

# Change active pane
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Change windows using SHIFT + ALT + H/L
bind-key -n M-H previous-window
bind-key -n M-L next-window
