# Set leader key
set -g prefix C-j

set-option -g status-position top
set -g mouse on
set -g base-index 1
set -g renumber-windows on
setw -g mode-keys vi

unbind R
bind R source-file ~/.config/tmux/.tmux.conf

unbind r
bind r command-prompt "rename-window %%"
unbind %
bind % command-prompt "rename-session %%"

# Open panes in current directory
bind v split-window -h -c "#{pane_current_path}"
unbind '"'
bind b split-window -v -c "#{pane_current_path}"

# Change active pane
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Change windows using SHIFT + ALT + H/L
bind-key -n M-H previous-window
bind-key -n M-L next-window
