unbind r
bind r source-file ~/.tmux.conf

set-option -g status-position top
set -g mouse on
set -g base-index 1
# Set leader key
set -g prefix C-j

# VIM-style key-bindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
