--ozone-platform-hint=auto
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-quic
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,DiskCacheBackendExperiment:backend/simple,HardwareMediaKeyHandling,InlineScriptCache,ParallelDownloading,UsePersistentCacheForCodeCache,WaylandSessionManagement
--disable-features=Vulkan
