--ozone-platform=wayland
--enable-features=VaapiVideoDecoder,VaapiVideoDecodeLinuxGL,InlineScriptCache,AcceleratedVideoEncoder,VaapiVideoEncoder
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
