[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x555753"
blue = "0x729FCF"
cyan = "0x34E2E2"
green = "0x8AE234"
magenta = "0xAD7FA8"
red = "0xEF2929"
white = "0xEEEEEC"
yellow = "0xFCE94F"

[colors.normal]
black = "0x2E3436"
blue = "0x3465A4"
cyan = "0x06989A"
green = "0x4E9A06"
magenta = "0x75507B"
red = "0xCC0000"
white = "0xD3D7CF"
yellow = "0xC4A000"

[colors.primary]
background = "0x191F21"
foreground = "0xc5c8c6"

[colors.selection]
background = "0x565656"
text = "0xc5c8c6"

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi|~Search"
mods = "Shift"

[scrolling]
history = 10000

[window]
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
